version: '3.8'

services:

    #PHP8.3.0 + Apache + Composer
    app:
        build:
            context: .
            dockerfile: ./docker/php-apache/Dockerfile
        container_name: app
        restart: unless-stopped
        tty: true
        ports:
            - 80:80
            - 443:443
        volumes:
            # Pasta de trabalho
            - ./html:/var/www/html
            # Logs apache
            - ./docker/php-apache/apache/log:/var/log/apache2
            # php.ini scan this dir for additional .ini files /usr/local/etc/php/conf.d
            - ./docker/php-apache/php/php-parsed.ini:/usr/local/etc/php/conf.d/php-parsed.ini
        networks:
            - app-001

    #MySQL
    db:
        image: mysql:8.2.0
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: vertrigo
        volumes:
            # Base de dados
            - ./docker/mysql/db:/var/lib/mysql
            # my.cnf não tem necessidade de momentp
            # - ./docker/mysql:/etc
        networks:
            - app-001

#Docker Networks
networks:
    app-001:
        driver: bridge