version: '3.8'

# Services
services:

    # PHP8.3.0 + Apache + Composer
    app:
        build:
            context: .
            dockerfile: ./docker/php-apache/Dockerfile
        container_name: app
        restart: unless-stopped
        tty: true
        ports:
            - 80:80
            - 443:443
        volumes:
            # Pasta de trabalho
            - app-vol:/var/www/html
            # Logs apache
            - ./docker/php-apache/apache/log:/var/log/apache2
            # php.ini scan this dir for additional .ini files /usr/local/etc/php/conf.d
            - ./docker/php-apache/php/php-parsed.ini:/usr/local/etc/php/conf.d/php-parsed.ini
        networks:
            - app-net

    # MySQL
    db:
        image: mysql:8.2.0
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: vertrigo
        volumes:
            # Base de dados
            - db-vol:/var/lib/mysql
            # my.cnf não tem necessidade de momentp
            # - ./docker/mysql:/etc
        networks:
            - app-net

# Networks
networks:
    app-net:
        driver: bridge

# Volumes
volumes:
    # app
    app-vol:
        driver: local
        driver_opts:
          type: 'none'
          o: 'bind'
          device: './html'
    # db
    db-vol:
        driver: local
        driver_opts:
          type: 'none'
          o: 'bind'
          device: './docker/mysql/db'